START TRANSACTION;

-- Normalized tables for consultation history and vitals (no procedures)
CREATE TABLE IF NOT EXISTS `tbl_consultation_history` (
  `consultation_id` INT(11) NOT NULL,
  `present_illness` TEXT NULL,
  `past_medical_history` TEXT NULL,
  `past_surgical_history` TEXT NULL,
  `family_history` TEXT NULL,
  `social_history` TEXT NULL,
  `smoking_status` ENUM('Yes','No') NULL,
  `smoking_packs_per_day` VARCHAR(10) NULL,
  `alcohol_use` ENUM('Yes','No') NULL,
  `alcohol_frequency` VARCHAR(50) NULL,
  `drug_use` ENUM('Yes','No') NULL,
  `drug_type` VARCHAR(100) NULL,
  `sexual_activity` ENUM('Active','Not Active') NULL,
  `current_medications` TEXT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`consultation_id`),
  CONSTRAINT `fk_history_consultation` FOREIGN KEY (`consultation_id`) REFERENCES `tbl_consultations` (`consultation_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tbl_consultation_vitals` (
  `consultation_id` INT(11) NOT NULL,
  `height_cm` DECIMAL(5,2) NULL,
  `weight_kg` DECIMAL(5,2) NULL,
  `blood_pressure_mmHg` VARCHAR(15) NULL,
  `heart_rate_bpm` INT NULL,
  `spo2_percent` DECIMAL(5,2) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`consultation_id`),
  CONSTRAINT `fk_vitals_consultation` FOREIGN KEY (`consultation_id`) REFERENCES `tbl_consultations` (`consultation_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO tbl_roles (role_name)
SELECT 'admin'
WHERE NOT EXISTS (
  SELECT 1 FROM tbl_roles WHERE role_name = 'admin'
);

-- 2) Seed an initial admin user if none exists (default password: Admin@123 change on first login)
-- Note: Replace the password hash if needed. Hash below is for 'Admin@123' generated by PHP password_hash default.
SET @adminRoleId := (SELECT role_id FROM tbl_roles WHERE role_name = 'admin' LIMIT 1);

-- Upsert admin user by email (store plaintext temporarily; app will upgrade to bcrypt on first login)
INSERT INTO tbl_users (name, email, password, role_id, must_change_password, is_active)
VALUES ('System Admin', 'admin@gmail.com', 'password123', @adminRoleId, 1, 1)
ON DUPLICATE KEY UPDATE
  password = VALUES(password),
  role_id = VALUES(role_id),
  must_change_password = 1,
  is_active = 1;

COMMIT;

-- Admin role and seed admin user migration
-- Safe to run multiple times (uses NOT EXISTS guards)

START TRANSACTION;

-- 1) Ensure 'admin' role exists in tbl_roles
INSERT INTO tbl_roles (role_name)
SELECT 'admin'
WHERE NOT EXISTS (
	SELECT 1 FROM tbl_roles WHERE LOWER(role_name) = 'admin'
);

-- 2) Seed an initial admin user (force password change on first login)
-- Change these before running in production
SET @admin_email := 'admin@clinic.local';
SET @admin_name := 'System Admin';
-- BCrypt for the temporary password 'ChangeMeNow!2025' (please rotate immediately)
SET @password_hash := '$2y$10$2d1.8qk7nWZk0wQk0uUjQe8r0m3j7oQHh2r2aF9CzQpEo8y9p3o7e';

SET @admin_role_id := (SELECT role_id FROM tbl_roles WHERE LOWER(role_name) = 'admin' LIMIT 1);

INSERT INTO tbl_users (name, email, password, role_id, must_change_password, is_active)
SELECT @admin_name, @admin_email, @password_hash, @admin_role_id, 1, 1
WHERE NOT EXISTS (
	SELECT 1 FROM tbl_users WHERE email = @admin_email
);

COMMIT;

-- Clinical summary table for consultations (symptoms and final diagnosis)
CREATE TABLE IF NOT EXISTS `tbl_consultation_summary` (
  `consultation_id` INT(11) NOT NULL,
  `symptoms_text` TEXT NULL,
  `final_diagnosis` VARCHAR(255) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`consultation_id`),
  CONSTRAINT `fk_summary_consultation` FOREIGN KEY (`consultation_id`) REFERENCES `tbl_consultations` (`consultation_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
